# Generated by Django 6.0.3 on 2026-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, help_text='I/O pinek és opcionális diagnosztikai paraméterek'),
        ),
    ]
